---
# NOTE: BUILD_ROOT_LOC is the WORK_ROOT mentioned in the memo by Yan G.
BUILD_ROOT_LOC: '/root/dlg-lofar'

BUILD_ROOT_DALIUGE_LOC: '{{BUILD_ROOT_LOC}}/daliuge'
BUILD_ROOT_DALIUGE_BASE_LOC: '{{BUILD_ROOT_DALIUGE_LOC}}/docker/base'
BUILD_ROOT_DALIUGE_DFMS_LOC: '{{BUILD_ROOT_DALIUGE_LOC}}/docker/dfms'

BUILD_ROOT_PREFACTOR_DALIUGE_LOC: '{{BUILD_ROOT_LOC}}/prefactor-DALiuGE'
BUILD_ROOT_PREFACTOR_DALIUGE_LOFAR_DLG_BASE_LOC: '{{BUILD_ROOT_PREFACTOR_DALIUGE_LOC}}/lofar-dlg-base'
BUILD_ROOT_PREFACTOR_DALIUGE_LOFAR_DLG_LOC: '{{BUILD_ROOT_PREFACTOR_DALIUGE_LOC}}/lofar-dlg'

BUILD_ROOT_CALIB_LOC: '{{BUILD_ROOT_LOC}}/CALIB'

LOCAL_LOC: '/local'
LOCAL_DALIUGE_LOGICAL_GRAPHS_LOC: '{{LOCAL_LOC}}/daliuge-logical-graphs'
LOCAL_DATA_LOC: '{{LOCAL_LOC}}/data'
LOCAL_DATA_SMALL_LOC: '{{LOCAL_DATA_LOC}}/small'
LOCAL_SHARED_LOC: '{{LOCAL_LOC}}/shared'

LOCAL_WORKDIR_LOC: '{{LOCAL_LOC}}/workdir'
LOCAL_WORKDIR_DLG_LGWEB_LOC: '{{LOCAL_WORKDIR_LOC}}/dlg-lgweb'
LOCAL_WORKDIR_LOGS_LOC: '{{LOCAL_WORKDIR_LOC}}/logs'
LOCAL_SHARED_WORKDIR_LOC: '{{LOCAL_SHARED_LOC}}/workdir'
