---

- name: Retrieve raid firmware image from Dell downloads site
  get_url:
    url: "{{ dell_raid_url }}"
    dest: "/tmp"
    mode: 0755
  register: firmware_data

# todo: check raid controller not in use:
#   - check all mounts
#   - check mappings from device mapper
#   - lvm mounts

# Exit codes:
# 2: Update applied.
# 3: No update required.
- name: Execute the raid firmware upgrade
  command: "{{ firmware_data.dest }}"
  become: True
  register: result
  failed_when: result.rc not in [2, 3]
  changed_when: result.rc == 2

- name: Remove the raid firmware image
  file:
    path: "{{ firmware_data.dest }}"
    state: absent
