---
- include: setup.yml
- include: ceph-client.yml
- include: users.yml

- hosts: cluster_login
  remote_user: "{{ cluster_guest }}"
  become: yes
  roles:
    - role: openhpc_control

- hosts: cluster_batch
  remote_user: "{{ cluster_guest }}"
  become: yes
  roles:
    - role: openhpc_compute

- hosts: cluster
  remote_user: "{{ cluster_guest }}"
  become: yes
  roles:
    - role: openhpc_runtime
      slurm_partitions: "{{ openhpc_slurm_partitions }}"
